/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import arMessage from '../locales/ar/messages.json';
import enMessage from '../locales/en/messages.json';
import pt_BRMessage from '../locales/pt_BR/messages.json';
import zh_TWMessage from '../locales/zh_TW/messages.json';

export function getMessageFromLocale(locale: string) {
  switch (locale) {
    case 'ar':
      return arMessage;
    case 'en':
      return enMessage;
    case 'pt_BR':
      return pt_BRMessage;
    case 'zh_TW':
      return zh_TWMessage;
    default:
      throw new Error('Unsupported locale');
  }
}

export const defaultLocale = (() => {
  const locales = ['ar', 'en', 'pt_BR', 'zh_TW'];
  const firstLocale = locales[0];
  const defaultLocale = Intl.DateTimeFormat().resolvedOptions().locale.replace('-', '_');
  if (locales.includes(defaultLocale)) {
    return defaultLocale;
  }
  const defaultLocaleWithoutRegion = defaultLocale.split('_')[0];
  if (locales.includes(defaultLocaleWithoutRegion)) {
    return defaultLocaleWithoutRegion;
  }
  return firstLocale;
})();
