/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import arMessage from '../locales/ar/messages.json';
import enMessage from '../locales/en/messages.json';
import pt_BRMessage from '../locales/pt_BR/messages.json';
import zh_CNMessage from '../locales/zh_CN/messages.json';
import zh_HKMessage from '../locales/zh_HK/messages.json';
import zh_SGMessage from '../locales/zh_SG/messages.json';
import zh_TWMessage from '../locales/zh_TW/messages.json';

export function getMessageFromLocale(locale: string) {
  switch (locale) {
    case 'ar':
      return arMessage;
    case 'en':
      return enMessage;
    case 'pt_BR':
      return pt_BRMessage;
    case 'zh_CN':
      return zh_CNMessage;
    case 'zh_HK':
      return zh_HKMessage;
    case 'zh_SG':
      return zh_SGMessage;
    case 'zh_TW':
      return zh_TWMessage;
    default:
      throw new Error('Unsupported locale');
  }
}

export const defaultLocale = (() => {
  const locales = ['ar', 'en', 'pt_BR', 'zh_CN', 'zh_HK', 'zh_SG', 'zh_TW'];
  // Prefer navigator.language (browser UI language) over Intl.DateTimeFormat (date format locale)
  const browserLocale = (
    typeof navigator !== 'undefined' && navigator.language
      ? navigator.language
      : Intl.DateTimeFormat().resolvedOptions().locale
  ).replace('-', '_');
  // Exact match (e.g. 'zh_CN')
  if (locales.includes(browserLocale)) {
    return browserLocale;
  }
  // Match by language code without region (e.g. 'zh' -> triggers zh_CN mapping below)
  const localeWithoutRegion = browserLocale.split('_')[0];
  if (locales.includes(localeWithoutRegion)) {
    return localeWithoutRegion;
  }
  // Special: map generic 'zh' to 'zh_CN' (Simplified Chinese)
  if (localeWithoutRegion === 'zh') return 'zh_CN';
  // Default fallback to English
  return 'en';
})();
