/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type arMessage from '../locales/ar/messages.json';
import type enMessage from '../locales/en/messages.json';
import type pt_BRMessage from '../locales/pt_BR/messages.json';
import type zh_TWMessage from '../locales/zh_TW/messages.json';

export type MessageKey = keyof typeof arMessage &
  keyof typeof enMessage &
  keyof typeof pt_BRMessage &
  keyof typeof zh_TWMessage;

export type DevLocale = 'ar' | 'en' | 'pt_BR' | 'zh_TW';
